### ISSUE TITLE
Curious about colouring of datasource drop down

### ISSUE THREAD

**Issue by simonswine** [grafana/explore-profiles#106]
### Bug description

- **Grafana version:** Grafana Enterprise (production) 🔗 [v11.2.0-73830](https://github.com/grafana/grafana/commit/8d98c9eba79e66e371b0045f957804c12f201170)

- **Plugin version:** v0.1.5 - 29/07/2024, 01:00:00

### Steps to reproduce

In an instance with more than 3 data sources  open the drop down:

![image](https://github.com/user-attachments/assets/0b6555b4-7299-43ab-abf1-cd9f763251fc)

Don't understand why the top one is gray.

Seems to be the same for explore-logs dropdown.

**Comment by grafakus** [comment]
@simonswine can you see the same behaviour with the [official Design System component](https://developers.grafana.com/ui/latest/index.html?path=/story/forms-select--basic)?

**Comment by simonswine** [comment]
Yes I can see the same behaviour, so we probably need to take it there or see it is a feature.

**Comment by grafakus** [comment]
Will be fixed in https://github.com/grafana/design-system/issues/152
