### ISSUE TITLE
Adapt wording for splash screen for OSS 

### ISSUE THREAD

**Issue by simonswine** [grafana/explore-profiles#22]
![image](https://github.com/grafana/explore-profiles/assets/223048/303ac52f-36b5-483d-a420-b1abe4e85daa)

We should not have those references to Grafana Cloud pricing / Grafana Cloud Profiles.

**Comment by grafakus** [comment]
@simonswine Fixed by Dima in https://github.com/grafana/explore-profiles/pull/67 ?

**Comment by simonswine** [comment]
Yes fixed by #67
