### ISSUE TITLE
[bug] Error while retrieving the plugin settings

### ISSUE THREAD

**Issue by weisdd** [grafana/explore-profiles#266]
### Bug description

- **Grafana version:** 11.3.0
- **Plugin version:** 0.1.15

When switching to "Flame graph" or "Diff flame graph" tab in the "Explore profiles" view, Grafana (self-hosted) shows the following warning:

> Error while retrieving the plugin settings!
> Some features might not work as expected (e.g. flamegraph export options). Please try to reload the page, sorry for the inconvenience.

![Image](https://github.com/user-attachments/assets/c10c09b9-eade-47f2-8967-01a9785f0fab)

In Chrome Developer Console, I see two requests failing with 404 core:
- `GET https://<REDACTED>/api/plugins/grafana-llm-app/settings`
- `POST https://<REDACTED>/api/datasources/proxy/uid/pyroscope/settings.v1.SettingsService/Get`

I haven't noticed any broken functionality, just that warning.

### Steps to reproduce

1. Go to this URL: Explore -> Profiles -> Explore profiles (URI `/a/grafana-pyroscope-app/profiles-explorer`);
2. Click on "Flame graph" or "Diff flame graph".

#### Actual behaviour

Each time I switch to either of the tabs ("Flame graph" or "Diff flame graph"), the same warning appears:

> Error while retrieving the plugin settings!
> Some features might not work as expected (e.g. flamegraph export options). Please try to reload the page, sorry for the inconvenience.

#### Expected behaviour

No warnings.

**Comment by grafakus** [comment]
Hi @weisdd ! 
I need a bit more info in order to help you: How do you run Pyroscope server? Which version it is?

**Comment by weisdd** [comment]
@grafakus I run it on AKS:
- official chart (`grafana/pyroscope`), version `1.7.1`;
- pyroscope version `1.9.0`;
- microservices mode (`values-micro-services.yaml`);
- data is stored in Azure Storage Account, Workload Identity is for authentication.

**Comment by aleks-p** [comment]
Hey @weisdd, the issue here is likely related to how frontend requests are routed to the right Pyroscope component. I assume you are pointing frontend requests to the `query-frontend` or the `querier` component (kubernetes service), however the `/settings.v1.SettingsService` endpoint is fulfilled by a separate component called `tenant-settings`.

You could either deploy a special component (a gateway / proxy) that routes requests to the corresponding component or enable the `ingress` in the helm chart and then point the frontend at the ingress:

```
ingress:
  enabled: true
  className: ""
  hosts:
    - localhost
```

The resulting ingress will have these rules:
```
Rules:                                                                                                                                                                                                                                                                                                                                                                                    
   Host        Path  Backends                                                                                                                                                                                                                                                                                                                                                              
   localhost                                                                                                                                                                                                                                                                                                                                                                               
               /                                        pyroscope-query-frontend:4040 (192.168.194.123:4040,192.168.194.3:4040)                                                                                                                                                                                                                                                            
               /querier.v1.QuerierService/              pyroscope-query-frontend:4040 (192.168.194.123:4040,192.168.194.3:4040)                                                                                                                                                                                                                                                            
               /render                                  pyroscope-query-frontend:4040 (192.168.194.123:4040,192.168.194.3:4040)                                                                                                                                                                                                                                                            
               /render-diff                             pyroscope-query-frontend:4040 (192.168.194.123:4040,192.168.194.3:4040)                                                                                                                                                                                                                                                            
               /push.v1.PusherService/                  pyroscope-distributor:4040 (192.168.194.125:4040,192.168.194.6:4040)                                                                                                                                                                                                                                                               
               /ingest                                  pyroscope-distributor:4040 (192.168.194.125:4040,192.168.194.6:4040)                                                                                                                                                                                                                                                               
               /settings.v1.SettingsService/            pyroscope-tenant-settings:4040 (192.168.194.2:4040)                                                                                                                                                                                                                                                                                
               /adhocprofiles.v1.AdHocProfileService/   pyroscope-ad-hoc-profiles:4040 (192.168.194.121:4040)
```

A bit more info [here](https://github.com/grafana/pyroscope/blob/ebc732f5b5a3af3643616c07d1f3218989185893/operations/pyroscope/helm/pyroscope/templates/ingress.yaml#L1), we'll work on improving the docs in the meantime.

**Comment by weisdd** [comment]
@aleks-p ah, thanks for pointing that out! Indeed, we expose Pyroscope only to in-cluster workloads, and Grafana consumes data using the `pyroscope-query-frontend` service. I can certainly workaround that. Thanks!

**Comment by grafakus** [comment]
Thank you @aleks-p , closing.
