### ISSUE TITLE
[feature] add support for experimental investigation feature

### ISSUE THREAD

**Issue by matryer** [grafana/explore-profiles#299]
Explore Metrics and Explore Logs have introduced an experimental feature for collecting interesting signals together during an investigation. We would like to add support for Traces (and profiles):

- [ ] decide data model for v1-alpha API (work with @fcjack)
- [x] add UI support (same three dots menu) to allow people to add items to an investigation (see this on [internal Slack](https://raintank-corp.slack.com/archives/C07QD9LTDA9/p1730337206752759))
- [x] add a profile
- [x] decide what other things could be added

**Comment by grafakus** [comment]
**Checklist (for future reference):**
1. Open [a PR in the Investigations App repo](https://github.com/grafana/investigations-app/pull/3) to add a new target extension point
2. Locally: build the Investigations App with the code from the previous PR
3. Locally: add support for Investigations to your Explore app, for instance, like in [this PR](https://github.com/grafana/explore-profiles/pull/301). In `plugin.json`, the extension point id must match the changes made in (1)
4. Locally: in the Grafana code base, add a `custom.ini` file with the following: 
  ```ini
    app_mode = development
    
    [paths]
    plugins = /path/to/the/root/folder/with/all/the/plugins
    
    [feature_toggles]
    enable=appSidecar
    appSidecar=true
  ```

Investigations is currently under the `appSidecar` feature flag. Also, make sure that the plugins folder contains the code for the Investigations App and the plugin to which you want to add support. E.g.:
![Image](https://github.com/user-attachments/assets/a7a40a28-ca7a-4055-b10e-ebdf753792c5)

5. Start the local Grafana
6. Start the dev of your plugin
7. Et voilà!
