### ISSUE TITLE
[bug] Preset selection dropdown shows wrong value, after selecting auto presets

### ISSUE THREAD

**Issue by simonswine** [grafana/explore-profiles#309]
### Bug description

- **Grafana version:** v11.4.0-79828
- **Plugin version:** v0.1.17

When selecting the auto-select options, it appears to be jumping back to the previously use preset.

### Steps to reproduce

* Open any "Diff flamegraph view"
* Select a "Last Hour - 30 min window". 

#### Actual behaviour
* 
* Now select "auto-select 25% or auto-select whole range", the preset drop down value will jump back to the "Last Hour - 30 min window" value, while still showing the one that was autoselect in the rest of the comparison. 

### Expected behaviour

* It should show the auto presets or maybe the "Choose a preset" value instead

https://github.com/user-attachments/assets/65d1bbf1-6c09-4d86-aa12-b73e4c3fbce8

**Comment by grafakus** [comment]
@simonswine I can't reproduce the issue shown in the video. In which env have you seen the problem?
