### ISSUE TITLE
Create distinction between user and admin settings

### ISSUE THREAD

**Issue by Rperry2174** [grafana/explore-profiles#38]
In https://github.com/grafana/pyroscope-app-plugin/pull/87

we created the ability to change a org-wide setting for admins. As of right now this settings page only shows up for admins to begin with. 

We should update the settings page to distinguish between two types of settings:
- admin settings (i.e. org wide things like disabling flamegraph.com export) 
- user settings (i.e. things like https://github.com/grafana/pyroscope-app-plugin/issues/89 -- where a user sets their "default app" )

This could be done either by making admin settings conditionally read-only or perhaps showing them on two separate tabs on the same page (one for admin and one for user)

**Comment by grafakus** [comment]
@simonswine is this issue still relevant? We have a single page for user settings only.

**Comment by simonswine** [comment]
I don't think it is relevant anytmore, I do think it is partly implemetned. It would be good to document some where, what our "settings" there are:

- user-settings: I would say that are things stored in the cookie (?), like the history of datasource selection and 
- admin-settings: Our admin page (store in the backend)
