### ISSUE TITLE
Enhance UI Persistence for Tab and Datasource Selections

### ISSUE THREAD

**Issue by korniltsev** [grafana/explore-profiles#42]
### Feature description

**Is your feature request related to a problem? Please describe.**

Yes, every time I open the new UI, I find myself having to manually click on the "flamegraph" tab and select the "dev" datasource. This repetitive action becomes tedious over time.

**Describe the solution you'd like**

I would like the UI to remember my last selections regarding the tab and datasource. This way, when I reopen the UI, it automatically displays the "flamegraph" tab with the "dev" datasource selected, or provides a mechanism to set default selections for these elements.

### Alternatives considered

**Describe alternatives you've considered**

**Comment by grafakus** [comment]
@korniltsev the data source part has been done in https://github.com/grafana/explore-profiles/pull/60

We're starting UX research and we will likely modify/replace all the "tabs".
Do you agree if we close this issue for now and revisit it in the future?

**Comment by korniltsev** [comment]
>  Do you agree if we close this issue for now and revisit it in the future?

I think we should either keep #42 open. 

Or Close it and create a new one for a case:
```
An experienced user does not want explore.
After "single view" was removed the user is now forced to do extra clicks to open "flamegraph" tab ("Single view replacement").
Because There is not enough space at the first row (occupied by tabbar), the UI is now inconsistent (Before https://github.com/grafana/explore-profiles/pull/70 the time picker is inconsistent jumps left and right between 1 and 2 rows depending on it's value. After PR 70, now the tab bar is inconsistent and sometimes collapsed and sometimes not depending on the value in time picker)
```

**Comment by grafakus** [comment]
Let's close this one and create a new issue for experienced users.

It's going to help to differentiate which problems for which target audience. Thx!
