### ISSUE TITLE
Handle no Pyroscope datasource more gracefully

### ISSUE THREAD

**Issue by simonswine** [grafana/explore-profiles#73]
### Bug description

We should be more helpful when there is no Pyroscope data source available:

After X ing this splash screen:

![image](https://github.com/user-attachments/assets/28c81577-3cc5-4b7f-a9fd-2e4777e87cde)

I get a query error:

![image](https://github.com/user-attachments/assets/767a3bfe-cef8-49f9-8044-526b5be69cf9)

Comparison diff view show this:

![image](https://github.com/user-attachments/assets/be698815-9241-479a-aad4-addec9c07b41)

### Steps to reproduce

1. Start an empty Grafana instance `docker run -p 3000:3000 grafana/grafana`
3. Goto:  Admin -> Plugins and Data -> Plugins install Explore-Profiles 
4. Naviagate to the plugin without a Pyroscope data source created

Grafana: Grafana v11.1.0 (5b85c4c2fc)
Explore-Profiles: v0.1.2

**Comment by grafakus** [comment]
Let's do the same: https://grafana.com/blog/2023/10/31/create-a-logs-app-plugin-with-grafana-scenes-and-grafana-loki/#home-page-of-the-scene
