### ISSUE TITLE
Avoid majority of the no data panels in the grid

### ISSUE THREAD

**Issue by simonswine** [grafana/explore-profiles#74]
The new Explore Profiles view is not filtering down the panels that are shown fully down to the metadata it holds. 

From the series endpoint it know which {

### Steps to reproduce

1. Go to this URL: https://play.grafana.org/a/grafana-pyroscope-app/profiles-explorer
2. Select the different profile types in the dropdown:
3. Observe how "no data" is shown

#### Actual behaviour

This is the `Series` result for profile types that contain process_cpu

```
[{"name":"service_name","value":"ebpf"},{"name":"__profile_type__","value":"process_cpu:cpu:nanoseconds:cpu:nanoseconds"}]
[{"name":"service_name","value":"load-generator"},{"name":"__profile_type__","value":"process_cpu:cpu:nanoseconds:cpu:nanoseconds"}]
[{"name":"service_name","value":"load-generator"},{"name":"__profile_type__","value":"process_cpu:samples:count:cpu:nanoseconds"}]
[{"name":"service_name","value":"pyroscope-rideshare-dotnet"},{"name":"__profile_type__","value":"process_cpu:cpu:nanoseconds:cpu:nanoseconds"}]
[{"name":"service_name","value":"pyroscope-rideshare-go"},{"name":"__profile_type__","value":"process_cpu:cpu:nanoseconds:cpu:nanoseconds"}]
[{"name":"service_name","value":"pyroscope-rideshare-go"},{"name":"__profile_type__","value":"process_cpu:samples:count:cpu:nanoseconds"}]
[{"name":"service_name","value":"pyroscope-rideshare-java"},{"name":"__profile_type__","value":"process_cpu:cpu:nanoseconds:cpu:nanoseconds"}]
[{"name":"service_name","value":"pyroscope-rideshare-python"},{"name":"__profile_type__","value":"process_cpu:samples:count::milliseconds"}]
[{"name":"service_name","value":"pyroscope-rideshare-ruby"},{"name":"__profile_type__","value":"process_cpu:samples:count::milliseconds"}]
```

We can see that for profile_cpu:cpu: the ones with data are the 5 from the list with "process_cpu:cpu:nanoseconds:cpu:nanoseconds"
 
![image](https://github.com/user-attachments/assets/6885e74a-95d5-4183-9540-154ce5149e70)
 
Then we switch to the first samples `process_cpu:samples:count:cpu:nanoseconds`:

![image](https://github.com/user-attachments/assets/ba6f499c-ef27-4d20-8448-627c49492cd8)

And the second samples `process_cpu:samples:count::milliseconds`, the two from the series call:

![image](https://github.com/user-attachments/assets/fbe3d786-0c02-43cf-985f-5b768129cb62)

#### Expected behaviour

* Samples should only show up once, (let's ignore that for now, that is backend problem https://github.com/grafana/pyroscope/issues/3319)
* Where the metadata shows us that the profile is not existing we should skip it from grid.

**Comment by grafakus** [comment]
Fixed in [v0.1.4](https://github.com/grafana/explore-profiles/blob/main/CHANGELOG.md#014-2024-07-25)
