### ISSUE TITLE
[bug] Pyroscope data-source not found after the plugin is installed

### ISSUE THREAD

**Issue by hazra-mms** [grafana/explore-profiles#84]
### Bug description

We have installed the plugin in our grafana infrastructure, we are having datasource for pyroscope already enabled but the plugin explore view doesn't find the datasource. Hence we can not use this.
### Steps to reproduce

Install the plugin following https://grafana.com/grafana/plugins/grafana-pyroscope-app/?tab=installation ( we installed manually and through plugin section in the helm chart).
Navigate to Profiles --> Explore Profiles

#### Actual behaviour

Error `TypeError: Failed to fetch`
![image](https://github.com/user-attachments/assets/11c9c1e3-e91e-4c17-88f0-bd7180d4ae1d)

Error in developer console in chrome
![image](https://github.com/user-attachments/assets/9debe1c9-41f0-4c2f-8bea-a613c4780879)

#### Expected behaviour

I expect the UI would load the profile correctly as the pyrooscope data source is configured already.

**Comment by simonswine** [comment]
Do you mind sharing ...
* ... if the datasource config page like in the screenshot says "Type: Grafana Pyroscope"
* ... if the test of the datasource is successful
* ... the version of Grafana you are running

![image](https://github.com/user-attachments/assets/a319df3a-889f-47dc-a7f0-4209bce6f1f4)

Thanks that should help us find the problem 🙂

**Comment by hazra-mms** [comment]
Thanks for your reply, please find the details.
Our pyroscope setup is working and we can get the details from the explore view also. It's just issues with the plugin that we face.
![image](https://github.com/user-attachments/assets/3a385440-1c33-4f67-97eb-804e0febbd45)

We are running Grafana version 10.4.3 which is configured using the helm chart.
![image](https://github.com/user-attachments/assets/2f1164a1-5f00-4d79-8bc7-237dccc67bb1)

In case you need any further information please let me know.

**Comment by grafakus** [comment]
Hi @hazra-mms, 

Thank you for the info, may I also ask you to share:
- the URL of the browser after trying to access the "Explore Profiles" page
- the full URL of the request that fails, the one that ends up with `/Series` on your screenshot
?

Thanks, we're still trying to figure out where the problem could be.

**Comment by hazra-mms** [comment]
Hi @grafakus ,

Sorry for the delay, please find the information below.

https://<redacted>/grafana/a/grafana-pyroscope-app/profiles-explorer?searchText=&layout=grid&hideNoData=off&explorationType=all&var-serviceName=&var-profileMetricId=process_cpu:cpu:nanoseconds:cpu:nanoseconds&var-dataSource=pyroscope

url for failing request contains:
http://localhost/grafana/api/datasources/proxy/uid/pyroscope/querier.v1.QuerierService/Series

Not sure why localhost is used here.

**Comment by ifrost** [comment]
Thanks @hazra-mms. Would you mind sharing part of your settings.ini file in `[server]` section? The `localhost` is taken from `root_url` config which [by default is](https://github.com/grafana/grafana/blob/ac5ebe6e4d16618764470d891ca0de91f7723a35/conf/defaults.ini#L51): 

```
root_url = %(protocol)s://%(domain)s:%(http_port)s/
```

By setting domain/protocol to:

```
[server]
http_port = 80
domain = grafana
```

or 

```
[server]
http_port = 80
root_url = http://grafana/
```

I was able to load the plugin from https://grafana/...:

![Image](https://github.com/user-attachments/assets/3e379ccc-becf-4a6d-9105-d7c4f3e52c69)


Also, do you have `serve_from_sub_path` set in your settings?

**Comment by ifrost** [comment]
We've closed this issue since it needs more information and hasn't had any activity recently. Feel free to re-open it after you you add more information.
