### ISSUE TITLE
[bug]  when I hit refresh button, the "Explain flamegraph" changes it's "new" badger color 

### ISSUE THREAD

**Issue by korniltsev** [grafana/explore-profiles#99]
### Bug description

- **Grafana version:** 
- **Plugin version:** 

When I hit refresh button, the "Explain flamegraph" changes it's "new" badger color  from orange to gray and back
This is distracting and unnecessary.

### Steps to reproduce

- hit "refresh" button

#### Expected behaviour

The button does not blink and not distracts

**Comment by korniltsev** [comment]
Also flamegraph pane title adds "..." for some reason

Goes from "profiles-dev-003/ingester flame graph (cpu)" to "profiles-dev-003/ingester flame graph (cpu)..." and back to "profiles-dev-003/ingester flame graph (cpu)"
This is not needed

**Comment by grafakus** [comment]
Two little things:
1. We are going to remove the "new" badge, the feature is already a few months old. it's not new anymore :)
2. The change of the button's color indicates a change of state state: it's disabled (grey) when loading new data. This is for visual feedback, to indicate to the user it's inactive.
